apiVersion: v1
kind: Template
metadata:
  name: ptrans 
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: ptrans-config 
  data: 
    conf: |-
      services=udp,tcp,statsd
      services.port.udp=5140
      services.port.tcp=5140
      services.statsd.port=8125
      metrics.url=${HAWKULAR_METRICS_ENDPOINT}
      metrics.tenant.send=true
      metrics.tenant=default
      metrics.auth.enabled=${AUTHENTICATION}
      metrics.auth.id=${HAWKULAR_USERNAME}
      metrics.auth.secret=${HAWKULAR_PASSWORD}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: hawkers
  spec:
    strategy:
      type: Rolling
    triggers:
      - type: ConfigChange
    replicas: 1
    selector:
      deploymentconfig: hawkers
    template:
      metadata:
        labels:
          deploymentconfig: hawkers
      spec:
        volumes:
          - name: config-volume
            configMap:
              name: ptrans-config
        containers:
          - name: ptrans
            image: quay.io/mikz/hawkers
            command: 
            - java
            - -jar
            - ptrans-all.jar
            - -c
            - /etc/ptrans/conf
            volumeMounts:
            - name: config-volume
              mountPath: /etc/ptrans/
- kind: "Service"
  apiVersion: "v1"
  metadata:
    name: "hawkers"
  spec:
    selector:
      deploymentconfig: hawkers
    ports:
      - name: "statsd-udp"
        protocol: "UDP"
        port: 8125
        targetPort: 8125
      - name: "statsd-tcp"
        protocol: "TCP"
        port: 8125
        targetPort: 8125
      - name: "syslog-tcp"
        protocol: "TCP"
        port: 5140
        targetPort: 5140
      - name: "syslog-udp"
        protocol: "UDP"
        port: 5140
        targetPort: 5140
parameters:
- name:  HAWKULAR_METRICS_ENDPOINT
  required: true
- name:  AUTHENTICATION
  value: "false"
  required: true
- name:  HAWKULAR_USERNAME
  value: ""
- name:  HAWKULAR_PASSWORD
  value: ""
